<?php
// complete_reservation.php
// หน้าต่างประมวลผลการจองและอนุมัติการจ่ายเงินขั้นสุดท้าย
// Final processing page to save reservation and payment in the database

// เชื่อมต่อฐานข้อมูล (Require database connection logic)
require 'config/db_connect.php';
// เริ่มต้นใช้งาน Session (Require session management)
require 'includes/auth_session.php';
// ตรวจสอบว่าเข้าระบบหรือยัง ไม่เช่นนั้นเด้งออก (Enforce login check, otherwise redirect to login page)
checkLogin();

// ตัวแปรเก็บสถานะความสำเร็จของคำสั่งเซฟลงฐานข้อมูล (Boolean flag to track success of the transaction)
$success = false;
// ตัวแปรสำหรับเก็บข้อความแจ้งสถานะเมื่อเกิดข้อผิดพลาด (Variable to hold error message if an exception occurs)
$error_msg = "";

// ตรวจสอบว่าเป็นการส่งข้อมูลฟอร์มมาจากหน้า Payment ด้วยวิธี POST (Check if request method is POST)
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // นำดึง User ID ที่ Login ค้างไว้มาเตรียมรันคำสั่ง (Retrieve logged in User ID from session)
    $user_id = $_SESSION['user_id'];
    
    // ดึงค่าการจองต่างๆ ที่ส่งมาจาก Form แบบซ่อนตัว (Retrieve all hidden inputs from the payload)
    $table_id = $_POST['table_id']; // รหัสโต๊ะ (Table ID)
    $date = $_POST['date']; // วันที่ (Date)
    $time = $_POST['time']; // เวลา (Time)
    $guests = $_POST['guests']; // จำนวนแขก (Number of guests)
    
    // ข้อมูลการคิดเงิน (Payment specifics)
    $amount = $_POST['amount']; // จำนวนเงินโอน (Total deposit amount)
    $method = $_POST['payment_method']; // วิธีชำระเงิน (Chosen payment method)
    
    try {
        // เริ่มคำสั่ง Transaction เพื่อให้แน่ใจว่าถ้าผิดพลาดจะทำการ Rollback ข้อมูลกลับคืน 
        // Begin PDO Transaction to ensure data integrity across multiple tables
        $pdo->beginTransaction();
        
        // 1. Double check availability
        // (Skipping for brevity, but crucial in real apps)
        // 1. ควรตรวจสอบอย่างรอบคอบอีกครั้งว่าสถานะโต๊ะ ณ วินาทีนี้ว่างจริงหรือไม่ 
        // (Realworld app should re-validate table availability here to prevent double-booking)
        
        // 2. Create Reservation
        // เพิ่มข้อมูลบันทึกการจองลงตาราง reservations (Insert new record into reservations table)
        // บังคับสถานะตอนเซฟให้เป็นยืนยัน ('confirmed') ทันที (Set initial status directly to 'confirmed')
        $sql = "INSERT INTO reservations (user_id, table_id, reservation_date, reservation_time, guest_count, status) VALUES (?, ?, ?, ?, ?, 'confirmed')";
        $stmt = $pdo->prepare($sql);
        $stmt->execute([$user_id, $table_id, $date, $time, $guests]);
        
        // ดึงเลขไอดีการจองล่าสุดที่เพิ่งสร้างขึ้นมาเพื่อไปใช้เชื่อมตารางอื่น (Retrieve the new Reservation ID generated by Auto Increment)
        $reservation_id = $pdo->lastInsertId();
        
        // 3. Create Payment Record
        // นำ Reservation ID มาผูกกับการเซฟประวัติการชำระเงิน (Tie Reservation ID to create a Payment history record)
        $ref = strtoupper(uniqid('REF-')); // สมมุติรหัสเลขทะเบียนใบเสร็จอ้างอิงให้ดูสวยงามตายตัว (Mock up a unique transaction reference code)
        // ถือว่าการจ่ายเสร็จสิ้น 'success' ทันที (Mark the payment status directly as 'success' for this demo)
        $sql_pay = "INSERT INTO payments (reservation_id, amount, method, status, transaction_ref) VALUES (?, ?, ?, 'success', ?)";
        $stmt_pay = $pdo->prepare($sql_pay);
        $stmt_pay->execute([$reservation_id, $amount, $method, $ref]);
        
        // 4. Update Table Status (Optional, if we want to lock it permanently)
        // But our api/get_tables.php already checks reservations table, so this is fine.
        // หมายเหตุ: ไม่จำเป็นต้องไปแก้ไขสถานะการเปิด/ปิดโต๊ะในตาราง เพราะ API เราเช็คจาก reservations อยู่แล้ว (Table status in DB isn't strictly locked as API logic reads reservation history dynamically)
        
        // จบการทำงานแบบเชื่อมโยง และยืนยันผลลัพธ์ลงตัวเก็บข้อมูล (Commit the entire transaction to save changes to the database natively)
        $pdo->commit();
        $success = true; // คืนค่าตัวแปรกลับเพื่อไปใช้แสดงผลหน้าสรุปจองบนบราวเซอร์ (Set success flag to true for UI rendering)
        
    } catch (Exception $e) {
        // ถ้าเกิดปัญหากลางคัน ระบบจะทำการยกเลิกคำสั่งก่อนหน้าทั้งหมดทิ้ง (Roll back changes on error to prevent partial saving)
        $pdo->rollBack();
        // เอาข้อผิดพลาดเก็บเป็น String (Capture the exact SQL exception message)
        $error_msg = "Booking Failed: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- กำหนด Title ของหน้ายืนยันการทำรายการจอง (Set static page title for Booking Status) -->
    <?php $page_title = 'Booking Status - NightOwl Pub'; ?>
    <!-- ดึงปลั๊กอินและสไตล์ชึต (Include generic HTML Head elements) -->
    <?php include 'includes/head.php'; ?>
</head>
<body class="bg-darker text-white font-sans min-h-screen flex flex-col items-center justify-center">
    <!-- เตรียมกล่องหลักไว้จัดกึ่งกลางให้สวยความ (Centered container box layout wrapper) -->
    <div class="container mx-auto px-4 text-center">
        <!-- ตรวจสอบตัวแปร Success ว่างานข้างบนทำสำเร็จหรือไม่ (Check if the PHP Transaction was successful) -->
        <?php if($success): ?>
            <!-- เมื่อสำเร็จ จะสร้างกล่องขอบสีเขียวเรืองแสงอ่อนๆ (Render a success card with neon green styling) -->
            <div class="bg-surface p-8 md:p-12 rounded-lg border-2 border-secondary shadow-[0_0_30px_rgba(0,255,65,0.2)] inline-block max-w-lg w-full">
                <!-- อีโมจิรูปติ๊กถูกขนาดใหญ่ (Big checkmark emoji) -->
                <div class="text-6xl mb-6">✅</div>
                <h1 class="text-3xl md:text-4xl font-bold text-secondary mb-4">Reservation Successful!</h1>
                <p class="text-gray-300 text-lg mb-6">Your table has been booked and deposit received.</p>
                <div class="bg-black/30 p-4 rounded mb-8">
                    <!-- แสดงคำอธิบายเลขแทรค (Label for Transaction Reference) -->
                    <p class="text-sm text-gray-500 uppercase tracking-wide">Transaction Reference</p>
                    <!-- นำเลขใบเสร็จที่เรา Generate ตอนเซฟดาต้าเบสมาแสดง (Display the mocked up Transaction reference) -->
                    <p class="text-2xl font-mono text-white tracking-widest"><?php echo $ref; ?></p>
                </div>
                <!-- ปุ่มพากลับไปหน้าแรก (Return Home button) -->
                <a href="index.php" class="btn w-full py-3 text-lg">Return to Home</a>
            </div>
        <?php else: ?>
            <!-- เมื่อเกิดข้อผิดพลาด จะสร้างกล่องสีแดงเรืองแสงอ่อนๆ (Render an error card with red styling if transaction failed) -->
            <div class="bg-surface p-8 md:p-12 rounded-lg border-2 border-error shadow-[0_0_30px_rgba(255,68,68,0.2)] inline-block max-w-lg w-full">
                <!-- อีโมจิรูปกากบาทขนาดใหญ่ (Big red cross emoji) -->
                <div class="text-6xl mb-6">❌</div>
                <h1 class="text-3xl md:text-4xl font-bold text-error mb-4">Booking Failed</h1>
                <!-- นำตัวแปร $error_msg มาแสดงผลให้ปลอดภัยต่อผู้ใช้ (Output error safely to avoid XSS) -->
                <p class="text-gray-300 text-lg mb-8"><?php echo htmlspecialchars($error_msg); ?></p>
                <!-- ปุ่มพากลับไปหน้าแรกเมื่อทำรายการไม่ผ่าน (Return Home dark button) -->
                <a href="index.php" class="btn w-full py-3 text-lg bg-gray-700 hover:bg-gray-600 text-white">Return to Home</a>
            </div>
        <?php endif; ?>
    </div>
    
    <!-- เครดิตลิขสิทธิ์จางๆ ด้านล่างสุด (Small footer text at the bottom) -->
    <div class="mt-8 text-gray-600 text-sm">
        &copy; 2026 NightOwl Pub
    </div>
</body>
</html>
